
[stripe]
secret_key = "sk_test_51PNaQI06CayRPFKYPJmBAsaCLOpogxLOZy3rup5ZwbPA19zq0A6oNxH8LRyUZcyBv07aa3yqWi8FN82xZ3lAQ0vi00IvR4tIz9"

[urls]
base_url = "http://localhost:8501"  # Update this to your production URL when deploying
